FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Train the model when building the image
RUN python train.py

EXPOSE 5000

CMD ["python", "app.py"]