# Use an official Python runtime as base
FROM python:3.9


# Set the working directory in the container
WORKDIR /app

# Copy the contents into the container
COPY . /app

# Install dependencies
RUN pip install -r requirements.txt

# Expose the port (if needed)
EXPOSE 5000

# Command to run the application
CMD ["python", "app.py"]
