name: Code Quality Check

on:
  push:
    branches: [ dev, test, main ]
  pull_request:
    branches: [ dev, test, main ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Flake8 Linter
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --max-line-length=127 --statistics
        
    - name: Fail if linting errors found
      run: |
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: false  # Ensures the workflow fails on errors
