# .github/workflows/code-quality.yml
name: Code Quality Check

on:
  pull_request:
    branches: [ dev, test, main ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --max-line-length=127 --statistics
        # exit-zero treats all errors as warnings - remove exit-zero to fail on all errors
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics