# .github/workflows/run-tests.yml
name: Run Tests

on:
  pull_request:
    branches: [ test, master ]
  workflow_run:
    workflows: ["Code Quality Check"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    # Only run if the code quality workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest test_app.py -v